# Generated by Django 2.0.4 on 2018-09-18 22:03

from django.db import migrations
from Apps.encuestador.constants import APP_NAME
from Apps.encuestador.models import ClassificationChoice
from Apps.encuestador.models import LanguageChoice
from Apps.encuestador.models import ResponseFormatType
from Apps.encuestador.models import ItemClassification


def insert_data(apps, schema_editor):

    ### Aqui van las clases para las que se llenaran los datos
    ItemClassification = apps.get_model(APP_NAME, 'ItemClassification')
    Parametric_master = apps.get_model(APP_NAME, 'Parametric_master')
    Trans_parametric_table = apps.get_model(APP_NAME, 'Trans_parametric_table')
    Response_format = apps.get_model(APP_NAME, 'Response_format')
    Item = apps.get_model(APP_NAME, 'Item')
    Trans_item = apps.get_model(APP_NAME, 'Trans_item')
    Instrument_header = apps.get_model(APP_NAME, 'Instrument_header')
    Trans_instrument_header = apps.get_model(APP_NAME, 'Trans_instrument_header')
    Instrument_structure_history = apps.get_model(APP_NAME, 'Instrument_structure_history')
    Company = apps.get_model(APP_NAME, 'Company')
    Client = apps.get_model(APP_NAME, 'Client')
    Surveys_by_client= apps.get_model(APP_NAME, 'Surveys_by_client')
    Customized_instrument= apps.get_model(APP_NAME, 'Customized_instrument')

    ###  Clean the data from the tables in which we introduce data in this method
    Instrument_structure_history.objects.all().delete()
    Trans_instrument_header.objects.all().delete()
    Instrument_header.objects.all().delete()

    Item.objects.all().delete()
    ItemClassification.objects.all().delete()
    Parametric_master.objects.all().delete()
    Trans_parametric_table.objects.all().delete()
    Response_format.objects.all().delete()
    Trans_item.objects.all().delete()
    Company.objects.all().delete()
    Client.objects.all().delete()
    Surveys_by_client.objects.all().delete()
    Customized_instrument.objects.all().delete()


    ### This list is used later for adding elements to the evaluation instrument
    itemsList  = []

    ################### Dimensions
    dim_adaptabilidad= ItemClassification(name="Adaptabilidad", type=ClassificationChoice.DIMENSION.value,
                                              i18n_code=LanguageChoice.ES.name)
    dim_adaptabilidad.save()
    dim_ambidestreza = ItemClassification(name="Ambidestreza", type=ClassificationChoice.DIMENSION.value,
                                       i18n_code=LanguageChoice.ES.name)
    dim_ambidestreza.save()
    dim_aceptaDiv = ItemClassification(name="Aceptación de la diversidad", type=ClassificationChoice.DIMENSION.value,
                                       i18n_code=LanguageChoice.ES.name)
    dim_aceptaDiv.save()
    dim_asociacion = ItemClassification(name="Asociación", type=ClassificationChoice.DIMENSION.value,
                                       i18n_code=LanguageChoice.ES.name)
    dim_asociacion.save()
    dim_complOrga = ItemClassification(name="Complejidad organizacional", type=ClassificationChoice.DIMENSION.value,
                                       i18n_code=LanguageChoice.ES.name)
    dim_complOrga.save()
    dim_compromiso = ItemClassification(name="Compromiso", type=ClassificationChoice.DIMENSION.value,
                                       i18n_code=LanguageChoice.ES.name)
    dim_compromiso.save()
    dim_comunEffect = ItemClassification(name="Comunicación efectiva", type=ClassificationChoice.DIMENSION.value,
                                       i18n_code=LanguageChoice.ES.name)
    dim_comunEffect.save()
    dim_confianza = ItemClassification(name="Confianza", type=ClassificationChoice.DIMENSION.value,
                                       i18n_code=LanguageChoice.ES.name)
    dim_confianza.save()
    dim_confrontacion = ItemClassification(name="Confrontación", type=ClassificationChoice.DIMENSION.value,
                                       i18n_code=LanguageChoice.ES.name)
    dim_confrontacion.save()
    dim_controlBuroc = ItemClassification(name="Control burocrático", type=ClassificationChoice.DIMENSION.value,
                                       i18n_code=LanguageChoice.ES.name)
    dim_controlBuroc.save()
    dim_curiosidad = ItemClassification(name="Curiosidad", type=ClassificationChoice.DIMENSION.value,
                                       i18n_code=LanguageChoice.ES.name)
    dim_curiosidad.save()
    dim_ejecucion = ItemClassification(name="Ejecución", type=ClassificationChoice.DIMENSION.value,
                                       i18n_code=LanguageChoice.ES.name)
    dim_ejecucion.save()
    dim_entorno = ItemClassification(name="Entorno", type=ClassificationChoice.DIMENSION.value,
                                       i18n_code=LanguageChoice.ES.name)
    dim_entorno.save()
    dim_estrategia = ItemClassification(name="Estrategia", type=ClassificationChoice.DIMENSION.value,
                                       i18n_code=LanguageChoice.ES.name)
    dim_estrategia.save()
    dim_flexiMental = ItemClassification(name="Flexibilidad Mental", type=ClassificationChoice.DIMENSION.value,
                                       i18n_code=LanguageChoice.ES.name)
    dim_flexiMental.save()
    dim_geneIdeas = ItemClassification(name="Generación de ideas", type=ClassificationChoice.DIMENSION.value,
                                       i18n_code=LanguageChoice.ES.name)
    dim_geneIdeas.save()
    dim_impIdeas = ItemClassification(name="Implementación de ideas", type=ClassificationChoice.DIMENSION.value,
                                       i18n_code=LanguageChoice.ES.name)
    dim_impIdeas.save()
    dim_liderazgo = ItemClassification(name="Liderazgo", type=ClassificationChoice.DIMENSION.value,
                                      i18n_code=LanguageChoice.ES.name)
    dim_liderazgo.save()
    dim_libertad = ItemClassification(name="Libertad", type=ClassificationChoice.DIMENSION.value,
                                       i18n_code=LanguageChoice.ES.name)
    dim_libertad.save()
    dim_manConfli = ItemClassification(name="Manejo de conflictos", type=ClassificationChoice.DIMENSION.value,
                                       i18n_code=LanguageChoice.ES.name)
    dim_manConfli.save()
    dim_metri = ItemClassification(name="Métricas y retribución", type=ClassificationChoice.DIMENSION.value,
                                       i18n_code=LanguageChoice.ES.name)
    dim_metri.save()
    dim_orientClie = ItemClassification(name="Orientación al cliente y al mercado", type=ClassificationChoice.DIMENSION.value,
                                       i18n_code=LanguageChoice.ES.name)
    dim_orientClie.save()
    dim_orienRiesg = ItemClassification(name="Orientación al riesgo", type=ClassificationChoice.DIMENSION.value,
                                       i18n_code=LanguageChoice.ES.name)
    dim_orienRiesg.save()
    dim_orientEmpre = ItemClassification(name="Orientación emprendedora", type=ClassificationChoice.DIMENSION.value,
                              i18n_code=LanguageChoice.ES.name)
    dim_orientEmpre.save()
    dim_orientRiesgo = ItemClassification(name="Orientación al riesgo", type=ClassificationChoice.DIMENSION.value,
                              i18n_code=LanguageChoice.ES.name)
    dim_orientRiesgo.save()
    dim_prioriz = ItemClassification(name="Priorización", type=ClassificationChoice.DIMENSION.value,
                              i18n_code=LanguageChoice.ES.name)
    dim_prioriz.save()
    dim_promIdeas = ItemClassification(name="Promoción de ideas", type=ClassificationChoice.DIMENSION.value,
                              i18n_code=LanguageChoice.ES.name)
    dim_promIdeas.save()
    dim_recono_exig = ItemClassification(name="Reconocimiento y exigencia", type=ClassificationChoice.DIMENSION.value,
                              i18n_code=LanguageChoice.ES.name)
    dim_recono_exig.save()
    dim_relacionam = ItemClassification(name="Relacionamiento", type=ClassificationChoice.DIMENSION.value,
                              i18n_code=LanguageChoice.ES.name)
    dim_relacionam.save()
    dim_respeto = ItemClassification(name="Respeto", type=ClassificationChoice.DIMENSION.value,
                              i18n_code=LanguageChoice.ES.name)
    dim_respeto.save()
    dim_simpli_agil = ItemClassification(name="Simplicidad y agilidad", type=ClassificationChoice.DIMENSION.value,
                              i18n_code=LanguageChoice.ES.name)
    dim_simpli_agil.save()
    dim_tolError = ItemClassification(name="Tolerancia al error", type=ClassificationChoice.DIMENSION.value,
                              i18n_code=LanguageChoice.ES.name)
    dim_tolError.save()
    dim_tom_decis = ItemClassification(name="Toma de decisiones", type=ClassificationChoice.DIMENSION.value,
                              i18n_code=LanguageChoice.ES.name)
    dim_tom_decis.save()
    dim_trabaj_equ = ItemClassification(name="Trabajo en equipo", type=ClassificationChoice.DIMENSION.value,
                              i18n_code=LanguageChoice.ES.name)
    dim_trabaj_equ.save()
    dim_veloc = ItemClassification(name="Velocidad", type=ClassificationChoice.DIMENSION.value,
                              i18n_code=LanguageChoice.ES.name)
    dim_veloc.save()

    ################### Categories
    cat_entorno_estrateg = ItemClassification(name="Entorno y estrategia", type=ClassificationChoice.CATEGORY.value,
                                              i18n_code=LanguageChoice.ES.name)
    cat_estructura = ItemClassification(name="Estructura", type=ClassificationChoice.CATEGORY.value,
                                              i18n_code=LanguageChoice.ES.name)
    cat_liderazgo = ItemClassification(name="Liderazgo y métricas", type=ClassificationChoice.CATEGORY.value,
                                              i18n_code=LanguageChoice.ES.name)
    cat_competOrganiz = ItemClassification(name="Competencias organizacionales", type=ClassificationChoice.CATEGORY.value,
                                       i18n_code=LanguageChoice.ES.name)
    cat_capacOrganiza = ItemClassification(name="Capacidades organizacionales",
                                           type=ClassificationChoice.CATEGORY.value,
                                           i18n_code=LanguageChoice.ES.name)
    cat_rasgos = ItemClassification(name="Rasgos culturales para la innovación",
                                           type=ClassificationChoice.CATEGORY.value,
                                           i18n_code=LanguageChoice.ES.name)
    cat_roles = ItemClassification(name="Roles comportamentales",
                                           type=ClassificationChoice.CATEGORY.value,i18n_code=LanguageChoice.ES.name)
    cat_entorno_estrateg.save()
    cat_estructura.save()
    cat_liderazgo.save()
    cat_competOrganiz.save()
    cat_capacOrganiza.save()
    cat_roles.save()
    cat_rasgos.save()

    ####################### Components
    comp_apropiacion= ItemClassification(name="Apropiación",type=ClassificationChoice.COMPONENT.value,i18n_code=LanguageChoice.ES.name)
    comp_apropiacion.save()
    comp_centralizacion= ItemClassification(name="Centralización",type=ClassificationChoice.COMPONENT.value,i18n_code=LanguageChoice.ES.name)
    comp_centralizacion.save()
    comp_considIndividualizada= ItemClassification(name="Consideración individualizada",type=ClassificationChoice.COMPONENT.value,i18n_code=LanguageChoice.ES.name)
    comp_considIndividualizada.save()
    comp_diferenFuncional= ItemClassification(name="Diferenciación funcional",type=ClassificationChoice.COMPONENT.value,i18n_code=LanguageChoice.ES.name)
    comp_diferenFuncional.save()
    comp_diferenVertical= ItemClassification(name="Diferenciación vertical",type=ClassificationChoice.COMPONENT.value,i18n_code=LanguageChoice.ES.name)
    comp_diferenVertical.save()
    comp_especializacion= ItemClassification(name="Especialización",type=ClassificationChoice.COMPONENT.value,i18n_code=LanguageChoice.ES.name)
    comp_especializacion.save()
    comp_estimuIntelec= ItemClassification(name="Estimulación intelectual",type=ClassificationChoice.COMPONENT.value,i18n_code=LanguageChoice.ES.name)
    comp_estimuIntelec.save()
    comp_formalizacion= ItemClassification(name="Formalización",type=ClassificationChoice.COMPONENT.value,i18n_code=LanguageChoice.ES.name)
    comp_formalizacion.save()
    comp_formulacion= ItemClassification(name="Formulación",type=ClassificationChoice.COMPONENT.value,i18n_code=LanguageChoice.ES.name)
    comp_formulacion.save()
    comp_influeIdealizada= ItemClassification(name="Influencia idealizada",type=ClassificationChoice.COMPONENT.value,i18n_code=LanguageChoice.ES.name)
    comp_influeIdealizada.save()
    comp_metricas= ItemClassification(name="Métricas",type=ClassificationChoice.COMPONENT.value,i18n_code=LanguageChoice.ES.name)
    comp_metricas.save()
    comp_motivacion= ItemClassification(name="Motivación inspiradora",type=ClassificationChoice.COMPONENT.value,i18n_code=LanguageChoice.ES.name)
    comp_motivacion.save()
    comp_profesionalismo= ItemClassification(name="Profesionalismo",type=ClassificationChoice.COMPONENT.value,i18n_code=LanguageChoice.ES.name)
    comp_profesionalismo.save()
    comp_retribucion= ItemClassification(name="Retribución",type=ClassificationChoice.COMPONENT.value,i18n_code=LanguageChoice.ES.name)
    comp_retribucion.save()

    # Parametric master
    likert_one_to_nine_master =Parametric_master(name="1-to-9 Likert",description="Escala likert del 1 al 9")
    likert_one_to_nine_master.save()

    likert_one_to_nine_1=Trans_parametric_table(parametric_master=likert_one_to_nine_master,option_label="Complementamente en desacuerdo",numeric_value=1, i18n_code=LanguageChoice.ES.name )
    likert_one_to_nine_2=Trans_parametric_table(parametric_master=likert_one_to_nine_master,option_label="",numeric_value=2, i18n_code=LanguageChoice.ES.name )
    likert_one_to_nine_3=Trans_parametric_table(parametric_master=likert_one_to_nine_master,option_label="",numeric_value=3, i18n_code=LanguageChoice.ES.name )
    likert_one_to_nine_4=Trans_parametric_table(parametric_master=likert_one_to_nine_master,option_label="",numeric_value=4, i18n_code=LanguageChoice.ES.name )
    likert_one_to_nine_5=Trans_parametric_table(parametric_master=likert_one_to_nine_master,option_label="",numeric_value=5, i18n_code=LanguageChoice.ES.name )
    likert_one_to_nine_6=Trans_parametric_table(parametric_master=likert_one_to_nine_master,option_label="",numeric_value=6, i18n_code=LanguageChoice.ES.name )
    likert_one_to_nine_7=Trans_parametric_table(parametric_master=likert_one_to_nine_master,option_label="",numeric_value=7, i18n_code=LanguageChoice.ES.name )
    likert_one_to_nine_8=Trans_parametric_table(parametric_master=likert_one_to_nine_master,option_label="",numeric_value=8, i18n_code=LanguageChoice.ES.name )
    likert_one_to_nine_9=Trans_parametric_table(parametric_master=likert_one_to_nine_master,option_label="Complementamente en deacuerdo",numeric_value=9, i18n_code=LanguageChoice.ES.name )

    #Save parametrics
    likert_one_to_nine_1.save()
    likert_one_to_nine_2.save()
    likert_one_to_nine_3.save()
    likert_one_to_nine_4.save()
    likert_one_to_nine_5.save()
    likert_one_to_nine_6.save()
    likert_one_to_nine_7.save()
    likert_one_to_nine_8.save()
    likert_one_to_nine_9.save()

    ######################### Response format
    one_to_nine_response= Response_format(parametric_table=likert_one_to_nine_master, name="1-to-9 Likert", type=ResponseFormatType.LIKERT_NINE)
    one_to_nine_response.save()

    # Items
    response_format_items_variable=one_to_nine_response

    # Capacidad organizativa subitems
    categoria=cat_capacOrganiza

    itemCapOrg1=Item(item_order=1, dimension=dim_ambidestreza,category=categoria, response_format=response_format_items_variable)
    itemCapOrg2=Item(item_order=2, dimension=dim_relacionam,category=categoria, response_format=response_format_items_variable)
    itemCapOrg3=Item(item_order=3, dimension=dim_orientClie,category=categoria, response_format=response_format_items_variable)
    itemCapOrg4=Item(item_order=4, dimension=dim_veloc,category=categoria, response_format=response_format_items_variable)
    itemCapOrg5=Item(item_order=5, dimension=dim_adaptabilidad,category=categoria, response_format=response_format_items_variable)
    itemCapOrg6=Item(item_order=6, dimension=dim_ejecucion,category=categoria, response_format=response_format_items_variable)
    itemCapOrg7=Item(item_order=7, dimension=dim_orientEmpre,category=categoria, response_format=response_format_items_variable)

    itemCapOrg1.save()
    itemCapOrg2.save()
    itemCapOrg3.save()
    itemCapOrg4.save()
    itemCapOrg5.save()
    itemCapOrg6.save()
    itemCapOrg7.save()

    transItemCapOrg1 = Trans_item(item=itemCapOrg1,
                           name="La compañía equilibra los esfuerzos en mantener y aprovechar sus habilidades, recursos y productos actuales con los esfuerzos en el desarrollo de nuevos conocimientos, habilidades y productos",
                           i18n_code=LanguageChoice.ES.name)
    transItemCapOrg2 = Trans_item(item=itemCapOrg2,
                          name="La compañía se caracteriza por establecer relaciones efectivas entre sus miembros y entre estos y el medio externo",
                          i18n_code=LanguageChoice.ES.name)
    transItemCapOrg3 = Trans_item(item=itemCapOrg3,
                       name="En términos generales, todos los colaboradores de la compañía trabajan en función el mercado y sus diferentes actores: clientes, competidores, proveedores, etc",
                       i18n_code=LanguageChoice.ES.name)
    transItemCapOrg4 = Trans_item(item=itemCapOrg4,
                       name="La compañía tiene la capacidad de desarrollar y lanzar nuevos productos más rápido que sus competidores",
                       i18n_code=LanguageChoice.ES.name)
    transItemCapOrg5 = Trans_item(item=itemCapOrg5,
                       name="La compañía aprende y se adapta de forma ágil a los entornos cambiantes siendo capaz de anticiparse a dichos cambios",
                       i18n_code=LanguageChoice.ES.name)
    transItemCapOrg6 = Trans_item(item=itemCapOrg6,
                       name="La compañía tiene la capacidad de pasar de una fase de iniciación, en la que se generan las ideas, a una fase de realización o implementación de las ideas",
                       i18n_code=LanguageChoice.ES.name)
    transItemCapOrg7 = Trans_item(item=itemCapOrg7,
                           name="En su cotidianidad la compañía integra la orientación a la innovación, la proactividad y la toma de riesgos",
                           i18n_code=LanguageChoice.ES.name)

    transItemCapOrg1.save()
    transItemCapOrg2.save()
    transItemCapOrg3.save()
    transItemCapOrg4.save()
    transItemCapOrg5.save()
    transItemCapOrg6.save()
    transItemCapOrg7.save()

    # Competencias organizacionales subitems
    categoria = cat_competOrganiz

    itemComOrg1 = Item(item_order=1, dimension=dim_comunEffect, category=categoria,
                       response_format=response_format_items_variable)
    itemComOrg2 = Item(item_order=2, dimension=dim_trabaj_equ, category=categoria,
                       response_format=response_format_items_variable)
    itemComOrg3 = Item(item_order=3, dimension=dim_comunEffect, category=categoria,
                       response_format=response_format_items_variable)
    itemComOrg4 = Item(item_order=4, dimension=dim_trabaj_equ, category=categoria,
                       response_format=response_format_items_variable)
    itemComOrg5 = Item(item_order=5, dimension=dim_tolError, category=categoria,
                       response_format=response_format_items_variable)
    itemComOrg6 = Item(item_order=6, dimension=dim_manConfli, category=categoria,
                       response_format=response_format_items_variable)
    itemComOrg7 = Item(item_order=7, dimension=dim_tolError, category=categoria,
                       response_format=response_format_items_variable)
    itemComOrg8 = Item(item_order=8, dimension=dim_manConfli, category=categoria,
                       response_format=response_format_items_variable)
    itemComOrg9 = Item(item_order=9, dimension=dim_tom_decis, category=categoria,
                       response_format=response_format_items_variable)
    itemComOrg10 = Item(item_order=10, dimension=dim_tom_decis, category=categoria,
                        response_format=response_format_items_variable)
    itemComOrg11 = Item(item_order=11, dimension=dim_simpli_agil, category=categoria,
                        response_format=response_format_items_variable)

    itemComOrg12 = Item(item_order=12, dimension=dim_simpli_agil, category=categoria,response_format=response_format_items_variable)
    itemComOrg13 = Item(item_order=13, dimension=dim_recono_exig, category=categoria,response_format=response_format_items_variable)
    itemComOrg14 = Item(item_order=14, dimension=dim_recono_exig, category=categoria,response_format=response_format_items_variable)
    itemComOrg15 = Item(item_order=15, dimension=dim_prioriz, category=categoria,response_format=response_format_items_variable)
    itemComOrg16 = Item(item_order=16, dimension=dim_prioriz, category=categoria,response_format=response_format_items_variable)

    itemComOrg1.save()
    itemComOrg2.save()
    itemComOrg3.save()
    itemComOrg4.save()
    itemComOrg5.save()
    itemComOrg6.save()
    itemComOrg7.save()
    itemComOrg8.save()
    itemComOrg9.save()
    itemComOrg10.save()
    itemComOrg11.save()
    itemComOrg12.save()
    itemComOrg13.save()
    itemComOrg14.save()
    itemComOrg15.save()
    itemComOrg16.save()


    transItemComOrg1 = Trans_item(item=itemComOrg1,
                                  name="La comunicación es trasparente, promueve la confianza y la idea de que el desacuerdo es aceptado en la compañía",
                                  i18n_code=LanguageChoice.ES.name)
    transItemComOrg2 = Trans_item(item=itemComOrg2,
                                  name="En la compañía es frecuente el trabajo compartido, colaborativo y participativo",
                                  i18n_code=LanguageChoice.ES.name)
    transItemComOrg3 = Trans_item(item=itemComOrg3,
                                  name="La comunicación promueve el intercambio de ideas entre individuos, entre diferentes equipos y diferentes áreas",
                                  i18n_code=LanguageChoice.ES.name)
    transItemComOrg4 = Trans_item(item=itemComOrg4,
                                  name="La compañía cuenta con equipos multifuncionales (I+D, diseño, ingeniería, comercial, etc.) que están trabajando en función de la  innovación y la creatividad",
                                  i18n_code=LanguageChoice.ES.name)
    transItemComOrg5 = Trans_item(item=itemComOrg5,
                                  name="La compañía acepta un margen razonable del error, especialmente cuando se comete probando cosas nuevas",
                                  i18n_code=LanguageChoice.ES.name)
    transItemComOrg6 = Trans_item(item=itemComOrg6,
                                  name="La compañía es capaz de tolerar y hacer un manejo constructivo del conflicto",
                                  i18n_code=LanguageChoice.ES.name)
    transItemComOrg7 = Trans_item(item=itemComOrg7,
                                  name="La compañía alienta a los trabajadores a asumir riesgos significativos y calculados sin temor a ser sancionados si se equivocan",
                                  i18n_code=LanguageChoice.ES.name)
    transItemComOrg8 = Trans_item(item=itemComOrg1,
                                  name="La compañía acepta diversos estilos de pensamiento entre sus miembros y fomenta la confrontación constructiva",
                                  i18n_code=LanguageChoice.ES.name)
    transItemComOrg9 = Trans_item(item=itemComOrg2,
                                  name="La compañía se caracteriza por la toma de decisiones participativa y acertada",
                                  i18n_code=LanguageChoice.ES.name)
    transItemComOrg10 = Trans_item(item=itemComOrg3,
                                  name="La compañía se caracteriza por la toma de decisiones rápidas y oportunas",
                                  i18n_code=LanguageChoice.ES.name)
    transItemComOrg11 = Trans_item(item=itemComOrg4,
                                  name="La compañía reconoce y valore el tiempo como un recurso valioso",
                                  i18n_code=LanguageChoice.ES.name)
    transItemComOrg12 = Trans_item(item=itemComOrg5,
                                  name="La compañía se caracteriza por tener procesos simples y ágiles",
                                  i18n_code=LanguageChoice.ES.name)
    transItemComOrg13 = Trans_item(item=itemComOrg6,
                                  name="En la compañía se es exigente  pero sin abusar de la autoridad y el poder",
                                  i18n_code=LanguageChoice.ES.name)
    transItemComOrg14 = Trans_item(item=itemComOrg7,
                                  name="En la compañía los logros son reconocidos, retribuidos y celebrados",
                                  i18n_code=LanguageChoice.ES.name)
    transItemComOrg15 = Trans_item(item=itemComOrg6,
                                  name="La compañía es capaz de hacer renuncias (abandonar proyectos, estrategias o acciones que ya no son prioritarias)",
                                  i18n_code=LanguageChoice.ES.name)
    transItemComOrg16 = Trans_item(item=itemComOrg7,
                                  name="En la acción organizacional la compañía generalmente establece prioridades",
                                  i18n_code=LanguageChoice.ES.name)

    transItemComOrg1.save()
    transItemComOrg2.save()
    transItemComOrg3.save()
    transItemComOrg4.save()
    transItemComOrg5.save()
    transItemComOrg6.save()
    transItemComOrg7.save()
    transItemComOrg8.save()
    transItemComOrg9.save()
    transItemComOrg10.save()
    transItemComOrg11.save()
    transItemComOrg12.save()
    transItemComOrg13.save()
    transItemComOrg14.save()
    transItemComOrg15.save()
    transItemComOrg16.save()

    # Entorno y Estrategias subitems
    categoria = cat_entorno_estrateg

    itemEntEst1 = Item(item_order=1, dimension=dim_entorno, category=categoria,response_format=response_format_items_variable)
    itemEntEst2 = Item(item_order=2, dimension=dim_estrategia, category=categoria,response_format=response_format_items_variable)
    itemEntEst3 = Item(item_order=3, dimension=dim_estrategia, category=categoria,response_format=response_format_items_variable)
    itemEntEst4 = Item(item_order=4, dimension=dim_estrategia, category=categoria,response_format=response_format_items_variable)
    itemEntEst5 = Item(item_order=5, dimension=dim_entorno, category=categoria,response_format=response_format_items_variable)
    itemEntEst6 = Item(item_order=6, dimension=dim_estrategia, category=categoria,response_format=response_format_items_variable)
    itemEntEst7 = Item(item_order=7, dimension=dim_estrategia, category=categoria,response_format=response_format_items_variable)
    itemEntEst8 = Item(item_order=8, dimension=dim_estrategia, category=categoria,response_format=response_format_items_variable)
    itemEntEst9 = Item(item_order=9, dimension=dim_estrategia, category=categoria,response_format=response_format_items_variable)
    itemEntEst10 = Item(item_order=10, dimension=dim_estrategia, category=categoria,response_format=response_format_items_variable)
    itemEntEst11 = Item(item_order=11, dimension=dim_entorno, category=categoria,response_format=response_format_items_variable)

    itemEntEst1.save()
    itemEntEst2.save()
    itemEntEst3.save()
    itemEntEst4.save()
    itemEntEst5.save()
    itemEntEst6.save()
    itemEntEst7.save()
    itemEntEst8.save()
    itemEntEst9.save()
    itemEntEst10.save()
    itemEntEst11.save()

    transItemEntEst1 = Trans_item(item=itemEntEst1,
                                  name="La compañía está inmersa en un ambiente competitivo muy intenso",
                                  i18n_code=LanguageChoice.ES.name)
    transItemEntEst2 = Trans_item(item=itemEntEst2,
                                  name="Se considera en el largo plazo el crecimiento por la vía de nuevos negocios",
                                  i18n_code=LanguageChoice.ES.name)
    transItemEntEst3 = Trans_item(item=itemEntEst3,
                                  name="Las políticas de la compañía favorecen la creatividad y la innovación",
                                  i18n_code=LanguageChoice.ES.name)
    transItemEntEst4 = Trans_item(item=itemEntEst4,
                                  name="En alta proporción, el crecimiento  de la compañía se hace vía innovación y diversificación de mercados",
                                  i18n_code=LanguageChoice.ES.name)
    transItemEntEst5 = Trans_item(item=itemEntEst5,
                                  name="La compañía se desenvuelve en un contexto en el que los gustos y preferencias de los clientes cambian con bastante rapidez",
                                  i18n_code=LanguageChoice.ES.name)
    transItemEntEst6 = Trans_item(item=itemEntEst6,
                                  name="Las metas y objetivos son conocidos por la mayoría de trabajadores de la compañía",
                                  i18n_code=LanguageChoice.ES.name)
    transItemEntEst7 = Trans_item(item=itemEntEst7,
                                  name="La innovación ha sido declarada  como pilar de la estrategia del negocio",
                                  i18n_code=LanguageChoice.ES.name)
    transItemEntEst8 = Trans_item(item=itemEntEst8,
                                  name="La misión y la visión de la empresa es entendida y apropiada por la mayoría de los trabajadores de la compañía",
                                  i18n_code=LanguageChoice.ES.name)
    transItemEntEst9 = Trans_item(item=itemEntEst9,
                                  name="La estrategia de la empresa es predominantemente prospectiva",
                                  i18n_code=LanguageChoice.ES.name)
    transItemEntEst10 = Trans_item(item=itemEntEst10,
                                  name="La misión y visión resultan inspiradores para la mayoría de trabajadores de la compañía",
                                  i18n_code=LanguageChoice.ES.name)
    transItemEntEst11 = Trans_item(item=itemEntEst11,
                                  name="Las tecnologías utilizadas por las empresas del sector (al que pertenece la empresa) cambian con bastante rapidez",
                                  i18n_code=LanguageChoice.ES.name)

    transItemEntEst1.save()
    transItemEntEst2.save()
    transItemEntEst3.save()
    transItemEntEst4.save()
    transItemEntEst5.save()
    transItemEntEst6.save()
    transItemEntEst7.save()
    transItemEntEst8.save()
    transItemEntEst9.save()
    transItemEntEst10.save()
    transItemEntEst11.save()

    # Estructura subitems
    categoria = cat_estructura

    itemEstru1 = Item(item_order=1, dimension=dim_complOrga, category=categoria,
                       response_format=response_format_items_variable)
    itemEstru2 = Item(item_order=2, dimension=dim_controlBuroc, category=categoria,
                       response_format=response_format_items_variable)
    itemEstru3 = Item(item_order=3, dimension=dim_complOrga, category=categoria,
                       response_format=response_format_items_variable)
    itemEstru4 = Item(item_order=4, dimension=dim_controlBuroc, category=categoria,
                       response_format=response_format_items_variable)
    itemEstru5 = Item(item_order=5, dimension=dim_complOrga, category=categoria,
                       response_format=response_format_items_variable)
    itemEstru6 = Item(item_order=6, dimension=dim_controlBuroc, category=categoria,
                       response_format=response_format_items_variable)

    itemEstru1.save()
    itemEstru2.save()
    itemEstru3.save()
    itemEstru4.save()
    itemEstru5.save()
    itemEstru6.save()

    transItemEstru1 = Trans_item(item=itemEstru1,
                                  name="La compañía se caracteriza por tener un amplio y diverso número de especialidades",
                                  i18n_code=LanguageChoice.ES.name)
    transItemEstru2 = Trans_item(item=itemEstru2,
                                  name="La compañía está apropiadamente descentraliza en la toma de decisiones",
                                  i18n_code=LanguageChoice.ES.name)
    transItemEstru3 = Trans_item(item=itemEstru3,
                                  name="La compañía dividida en un amplio número de unidades funcionales",
                                  i18n_code=LanguageChoice.ES.name)
    transItemEstru4 = Trans_item(item=itemEstru4,
                                  name="En la compañía existe un bajo nivel de formalización burocrática",
                                  i18n_code=LanguageChoice.ES.name)
    transItemEstru5 = Trans_item(item=itemEstru5,
                                  name="La planta de personal de la compañía cuenta con un número considerable de profesionales y tecnólogos",
                                  i18n_code=LanguageChoice.ES.name)
    transItemEstru6 = Trans_item(item=itemEstru6,
                                  name="En la compañía existen pocos niveles jerárquicos (plana)",
                                  i18n_code=LanguageChoice.ES.name)

    transItemEstru1.save()
    transItemEstru2.save()
    transItemEstru3.save()
    transItemEstru4.save()
    transItemEstru5.save()
    transItemEstru6.save()

    # Liderazgo y Metricas subitems
    categoria = cat_liderazgo

    itemLider1 = Item(item_order=1, dimension=dim_liderazgo, category=categoria,
                      response_format=response_format_items_variable)
    itemLider2 = Item(item_order=2, dimension=dim_metri, category=categoria,
                      response_format=response_format_items_variable)
    itemLider3 = Item(item_order=3, dimension=dim_liderazgo, category=categoria,
                      response_format=response_format_items_variable)
    itemLider4 = Item(item_order=4, dimension=dim_liderazgo, category=categoria,
                      response_format=response_format_items_variable)
    itemLider5 = Item(item_order=5, dimension=dim_metri, category=categoria,
                      response_format=response_format_items_variable)
    itemLider6 = Item(item_order=6, dimension=dim_liderazgo, category=categoria,
                      response_format=response_format_items_variable)

    itemLider1.save()
    itemLider2.save()
    itemLider3.save()
    itemLider4.save()
    itemLider5.save()
    itemLider6.save()

    transItemLider1 = Trans_item(item=itemLider1,
                                 name="La mayoría de los líderes de la compañía generan respeto, admiración y son considerados dignos de ser imitados",
                                 i18n_code=LanguageChoice.ES.name)
    transItemLider2 = Trans_item(item=itemLider2,
                                 name="El sistema y los mecanismos de medición comunica a los colaboradores lo que la compañía valora en términos de innovación y creatividad",
                                 i18n_code=LanguageChoice.ES.name)
    transItemLider3 = Trans_item(item=itemLider3,
                                 name="La mayoría de los líderes de la compañía proporciona a sus colaboradores un trabajo con sentido y significado ",
                                 i18n_code=LanguageChoice.ES.name)
    transItemLider4 = Trans_item(item=itemLider4,
                                 name="La mayoría de los lideres de la compañía estimula la creatividad y la innovación en su personal",
                                 i18n_code=LanguageChoice.ES.name)
    transItemLider5 = Trans_item(item=itemLider5,
                                 name="El sistema de compensación de la compañía esta orientado para que los colaboradores identifiquen comportamientos innovadores deseables",
                                 i18n_code=LanguageChoice.ES.name)
    transItemLider6 = Trans_item(item=itemLider6,
                                 name="La mayoría de los líderes de la compañía dan soporte y apoyo para el logro y desarrollo de sus colaboradores",
                                 i18n_code=LanguageChoice.ES.name)

    transItemLider1.save()
    transItemLider2.save()
    transItemLider3.save()
    transItemLider4.save()
    transItemLider5.save()
    transItemLider6.save()

    # Rasgos Culturales para la Inovacion subitems
    categoria = cat_rasgos

    itemRasgos1 = Item(item_order=1, dimension=dim_orienRiesg, category=categoria,
                       response_format=response_format_items_variable)
    itemRasgos2 = Item(item_order=2, dimension=dim_libertad, category=categoria,
                       response_format=response_format_items_variable)
    itemRasgos3 = Item(item_order=3, dimension=dim_flexiMental, category=categoria,
                       response_format=response_format_items_variable)
    itemRasgos4 = Item(item_order=4, dimension=dim_compromiso, category=categoria,
                       response_format=response_format_items_variable)
    itemRasgos5 = Item(item_order=5, dimension=dim_confianza, category=categoria,
                       response_format=response_format_items_variable)
    itemRasgos6 = Item(item_order=6, dimension=dim_curiosidad, category=categoria,
                       response_format=response_format_items_variable)
    itemRasgos7 = Item(item_order=7, dimension=dim_respeto, category=categoria,
                       response_format=response_format_items_variable)
    itemRasgos8 = Item(item_order=8, dimension=dim_confrontacion, category=categoria,
                       response_format=response_format_items_variable)
    itemRasgos9 = Item(item_order=9, dimension=dim_aceptaDiv, category=categoria,
                       response_format=response_format_items_variable)
    itemRasgos10 = Item(item_order=10, dimension=dim_asociacion, category=categoria,
                        response_format=response_format_items_variable)

    itemRasgos1.save()
    itemRasgos2.save()
    itemRasgos3.save()
    itemRasgos4.save()
    itemRasgos5.save()
    itemRasgos6.save()
    itemRasgos7.save()
    itemRasgos8.save()
    itemRasgos9.save()
    itemRasgos10.save()

    transItemRasgos1 = Trans_item(item=itemRasgos1,
                                  name="Me comporto adecuadamente en condiciones de incertidumbre y de desafíos difíciles",
                                  i18n_code=LanguageChoice.ES.name)
    transItemRasgos2 = Trans_item(item=itemRasgos2,
                                  name="Para la realización de mi trabajo yo cuento con autonomía, empoderamiento y participación",
                                  i18n_code=LanguageChoice.ES.name)
    transItemRasgos3 = Trans_item(item=itemRasgos3,
                                  name="Me considero una persona abierta a nuevas ideas y soy flexible cuando debo resolver problemas",
                                  i18n_code=LanguageChoice.ES.name)
    transItemRasgos4 = Trans_item(item=itemRasgos4,
                                  name="Me siento altamente comprometido con mi compañía",
                                  i18n_code=LanguageChoice.ES.name)
    transItemRasgos5 = Trans_item(item=itemRasgos5,
                                  name="Siento una alta seguridad emocional en mis relaciones de trabajo",
                                  i18n_code=LanguageChoice.ES.name)
    transItemRasgos6 = Trans_item(item=itemRasgos6,
                                  name="Tengo habilidad para percibir en la realidad cosas que normalmente los demás no observan",
                                  i18n_code=LanguageChoice.ES.name)
    transItemRasgos7 = Trans_item(item=itemRasgos7,
                                  name="Valoro las personas, les reconozco su experticia y conocimiento, considerando además su dignidad humana",
                                  i18n_code=LanguageChoice.ES.name)
    transItemRasgos8 = Trans_item(item=itemRasgos8,
                                  name="En situación de desacuerdo soy capaz de identificar similitudes y diferencias, hacerlas explícitas sin intimidarme ni intimidar, en busca de acuerdos",
                                  i18n_code=LanguageChoice.ES.name)
    transItemRasgos9 = Trans_item(item=itemRasgos9,
                                  name="Tengo la capacidad para actuar con personas de diferentes niveles jerárquicos, diferentes dependencias, diferentes formas de pensar y actuar",
                                  i18n_code=LanguageChoice.ES.name)
    transItemRasgos10 = Trans_item(item=itemRasgos10,
                                   name="Tengo la capacidad para conectar con éxito lo aparentemente inconexo",
                                   i18n_code=LanguageChoice.ES.name)

    transItemRasgos1.save()
    transItemRasgos2.save()
    transItemRasgos3.save()
    transItemRasgos4.save()
    transItemRasgos5.save()
    transItemRasgos6.save()
    transItemRasgos7.save()
    transItemRasgos8.save()
    transItemRasgos9.save()
    transItemRasgos10.save()

    # Roles comportamentales subitems
    categoria = cat_roles

    itemRoles1 = Item(item_order=1, dimension=dim_geneIdeas, category=categoria,
                      response_format=response_format_items_variable)
    itemRoles2 = Item(item_order=2, dimension=dim_geneIdeas, category=categoria,
                      response_format=response_format_items_variable)
    itemRoles3 = Item(item_order=3, dimension=dim_promIdeas, category=categoria,
                      response_format=response_format_items_variable)
    itemRoles4 = Item(item_order=4, dimension=dim_promIdeas, category=categoria,
                      response_format=response_format_items_variable)
    itemRoles5 = Item(item_order=5, dimension=dim_impIdeas, category=categoria,
                      response_format=response_format_items_variable)
    itemRoles6 = Item(item_order=6, dimension=dim_impIdeas, category=categoria,
                      response_format=response_format_items_variable)

    itemRoles1.save()
    itemRoles2.save()
    itemRoles3.save()
    itemRoles4.save()
    itemRoles5.save()
    itemRoles6.save()

    transItemRoles1 = Trans_item(item=itemRoles1,
                                 name="Busco cómo mejorar los procesos, tecnología, productos, servicios o relaciones de trabajo existentes",
                                 i18n_code=LanguageChoice.ES.name)
    transItemRoles2 = Trans_item(item=itemRoles2,
                                 name="Propongo ideas creativas",
                                 i18n_code=LanguageChoice.ES.name)
    transItemRoles3 = Trans_item(item=itemRoles3,
                                 name="Pruebo las nuevas ideas, tratando de evaluarlas",
                                 i18n_code=LanguageChoice.ES.name)
    transItemRoles4 = Trans_item(item=itemRoles4,
                                 name="Trato de persuadir a los demás de la importancia de una nueva idea o solución",
                                 i18n_code=LanguageChoice.ES.name)
    transItemRoles5 = Trans_item(item=itemRoles5,
                                 name="Trato de encontrar los fondos necesarios para poner en marcha las nuevas ideas",
                                 i18n_code=LanguageChoice.ES.name)
    transItemRoles6 = Trans_item(item=itemRoles6,
                                 name="Desarrollo planes y programas adecuados para implantar las nuevas ideas",
                                 i18n_code=LanguageChoice.ES.name)

    transItemRoles1.save()
    transItemRoles2.save()
    transItemRoles3.save()
    transItemRoles4.save()
    transItemRoles5.save()
    transItemRoles6.save()


    ##### Instrument headers and basic structure
    instrument_header = Instrument_header(version_name="1.0.a1",is_active=True)
    user_instructions= "No existen respuestas correctas, sólo queremos conocer su percepción sobre las cuestiones planteadas. Si de alguna de las preguntas no está totalmente seguro de la respuesta, no importa, nos interesa su estimación. Por favor, conteste todas las preguntas. En la mayoría de las preguntas se le proponen una serie de afirmaciones y se le pide que las valore puntuándolas entre 1 (si está en total desacuerdo con la afirmación) y 5 (si está totalmente de acuerdo con ella)."
    contact="Si tiene alguna duda, no dude en contactar con nosotros (danieljj@um.es; teléfono: <strong>+57 6 868887900 </strong>)"
    instrument_header.save()

    trans_instrument_header = Trans_instrument_header(instrument_header=instrument_header,user_instructions=user_instructions,i18n_code=LanguageChoice.ES.name, contact_info=contact )
    trans_instrument_header.save()

    # We add the items to the list of items in order to add those items to the instrument easily
    # Se comentan estas dos para probar que el servicio funciona
    #itemsList.append(itemRoles1)
    #itemsList.append(itemRoles2)
    itemsList.append(itemRoles3)
    itemsList.append(itemRoles4)
    itemsList.append(itemRoles5)
    itemsList.append(itemRoles6)

    itemsList.append(itemRasgos1)
    itemsList.append(itemRasgos2)
    itemsList.append(itemRasgos3)
    itemsList.append(itemRasgos4)
    itemsList.append(itemRasgos5)
    itemsList.append(itemRasgos6)
    itemsList.append(itemRasgos7)
    itemsList.append(itemRasgos8)
    itemsList.append(itemRasgos9)
    itemsList.append(itemRasgos10)

    itemsList.append(itemLider1)
    itemsList.append(itemLider2)
    itemsList.append(itemLider3)
    itemsList.append(itemLider4)
    itemsList.append(itemLider5)
    itemsList.append(itemLider6)

    itemsList.append(itemEstru1)
    itemsList.append(itemEstru2)
    itemsList.append(itemEstru3)
    itemsList.append(itemEstru4)
    itemsList.append(itemEstru5)
    itemsList.append(itemEstru6)

    itemsList.append(itemCapOrg1)
    itemsList.append(itemCapOrg2)
    itemsList.append(itemCapOrg3)
    itemsList.append(itemCapOrg4)
    itemsList.append(itemCapOrg5)
    itemsList.append(itemCapOrg6)
    itemsList.append(itemCapOrg7)

    itemsList.append(itemComOrg1)
    itemsList.append(itemComOrg2)
    itemsList.append(itemComOrg3)
    itemsList.append(itemComOrg4)
    itemsList.append(itemComOrg5)
    itemsList.append(itemComOrg6)
    itemsList.append(itemComOrg7)
    itemsList.append(itemComOrg8)
    itemsList.append(itemComOrg9)
    itemsList.append(itemComOrg10)
    itemsList.append(itemComOrg11)
    itemsList.append(itemComOrg12)
    itemsList.append(itemComOrg13)
    itemsList.append(itemComOrg14)
    itemsList.append(itemComOrg15)
    itemsList.append(itemComOrg16)

    itemsList.append(itemEntEst1)
    itemsList.append(itemEntEst2)
    itemsList.append(itemEntEst3)
    itemsList.append(itemEntEst4)
    itemsList.append(itemEntEst5)
    itemsList.append(itemEntEst6)
    itemsList.append(itemEntEst7)
    itemsList.append(itemEntEst8)
    itemsList.append(itemEntEst9)
    itemsList.append(itemEntEst10)
    itemsList.append(itemEntEst11)

    #Se agregan los items que ya se crearon al instrumento
    for item in itemsList:
        Instrument_structure_history_item= Instrument_structure_history(instrument_header=instrument_header,is_active=True,original_item=item,item_minor_version=1,new_item=item,previous_item=None,change_reason="version sept2018")
        Instrument_structure_history_item.save()


    # Se crea una compañia para hacer pruebas
    companyTest = Company(company_contact_name ="Contacto de prueba")
    companyTest.save()

    # Se crea un cliente de prueba
    clientTest = Client(company=companyTest,max_surveys=10, used_surveys=0, client_logo="",contact="Julia Clemencia" )
    clientTest.save()

    # Se crea un survey personalizado para el cliente
    customized_instrument= Customized_instrument (client=clientTest, company=companyTest,num_completed_responses=0,instrument_header=instrument_header)
    customized_instrument.save()

    # Se crean un survey para el cliente de prueba para hacer pruebas
    survey_by_client = Surveys_by_client(client=clientTest, acces_code="12345",customized_instrument=customized_instrument)
    survey_by_client.save()



class Migration(migrations.Migration):

    dependencies = [
        ('encuestador', '0001_initial'),
    ]

    operations = [

        #Excecute the methods that will insert the data in the database
        migrations.RunPython(insert_data),
    ]

