# Generated by Django 2.0.4 on 2018-09-19 00:49

import Apps.encuestador.models
from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# Apps.encuestador.migrations.0005_seedData_20180918_1704

class Migration(migrations.Migration):

    replaces = [('encuestador', '0001_initial'), ('encuestador', '0002_auto_20180918_1411'), ('encuestador', '0003_remove_item_hierarchicallevel'), ('encuestador', '0005_seedData_20180918_1704'), ('encuestador', '0006_auto_20180918_1844'), ('encuestador', '0008_auto_20180918_1931'), ('encuestador', '0009_auto_20180918_1935'), ('encuestador', '0010_auto_20180918_1936'), ('encuestador', '0011_remove_item_component1'), ('encuestador', '0012_auto_20180918_1938'), ('encuestador', '0013_auto_20180918_1940'), ('encuestador', '0014_auto_20180918_1946')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_surveys', models.IntegerField()),
                ('client_logo', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('has_iso', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_contact_name', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Customized_instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_completed_responses', models.IntegerField()),
                ('num_partial_responses', models.IntegerField()),
                ('resulting_URL', models.URLField()),
                ('total_of_instrument', models.IntegerField()),
                ('JSON_instrument_file', models.BinaryField()),
                ('Customized_description', models.TextField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Client')),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument_header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument_structure_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_minor_version', models.CharField(max_length=20)),
                ('id_new_item', models.IntegerField()),
                ('id_previous_item', models.IntegerField()),
                ('change_reason', models.TextField()),
                ('is_active', models.BooleanField()),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('id_instrument_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Instrument_header')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchicalLevel', models.IntegerField()),
                ('item_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Items_respon_by_participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_numeric', models.IntegerField()),
                ('answer_text', models.TextField()),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Parametric_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant_response_header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('last_update', models.DateTimeField()),
                ('is_complete', models.BooleanField()),
                ('comments', models.TextField()),
                ('is_admin_response', models.BooleanField()),
                ('acces_code', models.CharField(max_length=50)),
                ('id_customized_instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Customized_instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Response_format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('id_parametric_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Parametric_master')),
            ],
        ),
        migrations.CreateModel(
            name='Roles_by_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Trans_instrument_header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_description', models.TextField()),
                ('feature_description', models.TextField()),
                ('disclaimer', models.TextField()),
                ('user_instructions', models.TextField()),
                ('i18n_code', models.CharField(max_length=2)),
                ('id_instrument_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Instrument_header')),
            ],
        ),
        migrations.CreateModel(
            name='Trans_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('i18n_code', models.CharField(max_length=40)),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Trans_parametric_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_label', models.CharField(max_length=50)),
                ('option_group', models.CharField(max_length=50)),
                ('i18n_code', models.CharField(max_length=2)),
                ('numeric_value', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('id_parametric_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Parametric_master')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password_hashed', models.CharField(max_length=30)),
                ('organization', models.CharField(max_length=50)),
                ('organization_department', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('last_login', models.DateTimeField()),
                ('active_account', models.BooleanField()),
                ('registration_date', models.DateTimeField()),
                ('prefered_language', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='roles_by_user',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.User'),
        ),
        migrations.AddField(
            model_name='items_respon_by_participants',
            name='id_participant_response_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Participant_response_header'),
        ),
        migrations.AddField(
            model_name='item',
            name='id_response_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Response_format'),
        ),
        migrations.AddField(
            model_name='instrument_structure_history',
            name='id_orignal_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Item'),
        ),
        migrations.AddField(
            model_name='client',
            name='id_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Company'),
        ),
        migrations.CreateModel(
            name='ItemClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.IntegerField(choices=[(Apps.encuestador.models.ClassificationChoice(1), 1), (Apps.encuestador.models.ClassificationChoice(2), 2), (Apps.encuestador.models.ClassificationChoice(3), 3)])),
                ('i18n_code', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='id_category',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='item',
            name='id_component',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='item',
            name='id_dimension',
            field=models.IntegerField(default=None),
        ),
        migrations.RemoveField(
            model_name='item',
            name='hierarchicalLevel',
        ),

        migrations.RenameField(
            model_name='client',
            old_name='id_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='customized_instrument',
            old_name='id_client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='customized_instrument',
            old_name='id_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='instrument_structure_history',
            old_name='id_instrument_header',
            new_name='instrument_header',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='id_response_format',
            new_name='response_format',
        ),
        migrations.RenameField(
            model_name='items_respon_by_participants',
            old_name='id_item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='items_respon_by_participants',
            old_name='id_participant_response_header',
            new_name='participant_response_header',
        ),
        migrations.RenameField(
            model_name='participant_response_header',
            old_name='id_customized_instrument',
            new_name='customized_instrument',
        ),
        migrations.RenameField(
            model_name='response_format',
            old_name='id_parametric_table',
            new_name='parametric_table',
        ),
        migrations.RenameField(
            model_name='roles_by_user',
            old_name='id_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='roles_by_user',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='trans_instrument_header',
            old_name='id_instrument_header',
            new_name='instrument_header',
        ),
        migrations.RenameField(
            model_name='trans_item',
            old_name='id_item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='trans_parametric_table',
            old_name='id_parametric_master',
            new_name='parametric_master',
        ),
        migrations.RemoveField(
            model_name='instrument_structure_history',
            name='id_new_item',
        ),
        migrations.RemoveField(
            model_name='instrument_structure_history',
            name='id_orignal_item',
        ),
        migrations.RemoveField(
            model_name='instrument_structure_history',
            name='id_previous_item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='id_category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='id_component',
        ),
        migrations.RemoveField(
            model_name='item',
            name='id_dimension',
        ),
        migrations.AddField(
            model_name='instrument_structure_history',
            name='new_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_newItem', to='encuestador.Item'),
        ),
        migrations.AddField(
            model_name='instrument_structure_history',
            name='original_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_originalItem', to='encuestador.Item'),
        ),
        migrations.AddField(
            model_name='instrument_structure_history',
            name='previous_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_previousItem', to='encuestador.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='encuestador.ItemClassification'),
        ),
        migrations.AddField(
            model_name='item',
            name='component',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_component', to='encuestador.ItemClassification'),
        ),
        migrations.AddField(
            model_name='item',
            name='dimension',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_dimension', to='encuestador.ItemClassification'),
        ),
        migrations.AlterField(
            model_name='trans_item',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.RemoveField(
            model_name='trans_parametric_table',
            name='option_group',
        ),
        migrations.AlterField(
            model_name='parametric_master',
            name='end_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='response_format',
            name='type',
            field=models.CharField(choices=[(Apps.encuestador.models.ResponseFormatType('Yes/No'), 'Yes/No'), (Apps.encuestador.models.ResponseFormatType('Likert 9 points'), 'Likert 9 points'), (Apps.encuestador.models.ResponseFormatType('Likert 6 points'), 'Likert 6 points')], max_length=15),
        ),
        migrations.AlterField(
            model_name='trans_parametric_table',
            name='end_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='trans_item',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trans_item',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instrument_header',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instrument_structure_history',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='parametric_master',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trans_parametric_table',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
