# Generated by Django 2.0.4 on 2018-09-20 03:50

import Apps.encuestador.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_surveys', models.IntegerField()),
                ('client_logo', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('has_iso', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_contact_name', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Customized_instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_completed_responses', models.IntegerField()),
                ('num_partial_responses', models.IntegerField()),
                ('resulting_URL', models.URLField()),
                ('total_of_instrument', models.IntegerField()),
                ('JSON_instrument_file', models.BinaryField()),
                ('customized_description', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument_header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument_structure_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_minor_version', models.CharField(max_length=20)),
                ('change_reason', models.TextField()),
                ('is_active', models.BooleanField()),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('instrument_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Instrument_header')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.IntegerField(choices=[(Apps.encuestador.models.ClassificationChoice(1), 1), (Apps.encuestador.models.ClassificationChoice(2), 2), (Apps.encuestador.models.ClassificationChoice(3), 3)])),
                ('i18n_code', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Items_respon_by_participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_numeric', models.IntegerField()),
                ('answer_text', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Parametric_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant_response_header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('last_update', models.DateTimeField()),
                ('is_complete', models.BooleanField()),
                ('comments', models.TextField()),
                ('is_admin_response', models.BooleanField()),
                ('acces_code', models.CharField(max_length=50)),
                ('customized_instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Customized_instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Response_format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[(Apps.encuestador.models.ResponseFormatType('Yes/No'), 'Yes/No'), (Apps.encuestador.models.ResponseFormatType('Likert 9 points'), 'Likert 9 points'), (Apps.encuestador.models.ResponseFormatType('Likert 6 points'), 'Likert 6 points')], max_length=15)),
                ('parametric_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Parametric_master')),
            ],
        ),
        migrations.CreateModel(
            name='Roles_by_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Trans_instrument_header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_description', models.TextField()),
                ('feature_description', models.TextField()),
                ('disclaimer', models.TextField()),
                ('user_instructions', models.TextField()),
                ('i18n_code', models.CharField(max_length=2)),
                ('instrument_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Instrument_header')),
            ],
        ),
        migrations.CreateModel(
            name='Trans_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('i18n_code', models.CharField(max_length=40)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='encuestador.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Trans_parametric_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_label', models.CharField(max_length=50)),
                ('i18n_code', models.CharField(max_length=2)),
                ('numeric_value', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('parametric_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Parametric_master')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password_hashed', models.CharField(max_length=30)),
                ('organization', models.CharField(max_length=50)),
                ('organization_department', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('last_login', models.DateTimeField()),
                ('active_account', models.BooleanField()),
                ('registration_date', models.DateTimeField()),
                ('prefered_language', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='roles_by_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.User'),
        ),
        migrations.AddField(
            model_name='items_respon_by_participants',
            name='participant_response_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Participant_response_header'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='itemsByCategory', to='encuestador.ItemClassification'),
        ),
        migrations.AddField(
            model_name='item',
            name='component',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemsByComponent', to='encuestador.ItemClassification'),
        ),
        migrations.AddField(
            model_name='item',
            name='dimension',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='itemsByDimension', to='encuestador.ItemClassification'),
        ),
        migrations.AddField(
            model_name='item',
            name='response_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Response_format'),
        ),
        migrations.AddField(
            model_name='instrument_structure_history',
            name='new_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_newItem', to='encuestador.Item'),
        ),
        migrations.AddField(
            model_name='instrument_structure_history',
            name='original_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_originalItem', to='encuestador.Item'),
        ),
        migrations.AddField(
            model_name='instrument_structure_history',
            name='previous_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_previousItem', to='encuestador.Item'),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Company'),
        ),
    ]
